# Tensor Calculations

### **Topics to be covered:**
- Tensor Manipulation
- Tensor Arithmatics
- Tensor Linear Algebra </br>
    |__ Matrix Multiplication </br>
    |__ Dot Product </br>
    |__ Transpose </br>
    |__ Inverse and Determinant </br>
    |__ Eigenvalues & Eigenvectors </br>
    |__ Norms (L1 & L2) </br>

#### TENSOR MANIPULATION

In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
# Tensor Manipulation - Lists

# List to Tensor
list_data = [[1, 2], [3, 4]]
tensor = torch.tensor(list_data)
print(f"List Data:\n{list_data}\n")
print(f"Tensor Data:\n{tensor}")

List Data:
[[1, 2], [3, 4]]

Tensor Data:
tensor([[1, 2],
        [3, 4]])


In [3]:
# Tensor to List
tensor = torch.rand(2,2)
list_data = tensor.tolist()
print(f"Tensor Data:\n{tensor}\n")
print(f"List Data:\n{list_data}")

Tensor Data:
tensor([[0.8449, 0.8508],
        [0.4930, 0.3893]])

List Data:
[[0.8449119329452515, 0.8508446216583252], [0.49297523498535156, 0.38927632570266724]]


In [4]:
# Tensor Manipulation - Dataframes

# Tensor to Dataframe
tensor =  torch.rand(3,4)
df = pd.DataFrame(tensor.numpy())

print(f"Tensor Data:\n{tensor}\n")
print(f"Dataframe Data:\n{df}")

Tensor Data:
tensor([[0.3633, 0.1565, 0.9840, 0.6807],
        [0.0753, 0.3227, 0.3958, 0.3613],
        [0.4374, 0.3876, 0.7127, 0.3918]])

Dataframe Data:
          0         1         2         3
0  0.363299  0.156463  0.984049  0.680692
1  0.075331  0.322670  0.395755  0.361319
2  0.437434  0.387601  0.712728  0.391801


In [5]:
# Dataframe to Tensor
df = pd.DataFrame(np.random.rand(3,4))
tensor = torch.tensor(df.values)

print(f"Dataframe Data:\n{df}\n")
print(f"Tensor Data:\n{tensor}")

Dataframe Data:
          0         1         2         3
0  0.852245  0.463974  0.944048  0.349847
1  0.087060  0.210319  0.886866  0.925650
2  0.196148  0.927647  0.216891  0.354692

Tensor Data:
tensor([[0.8522, 0.4640, 0.9440, 0.3498],
        [0.0871, 0.2103, 0.8869, 0.9256],
        [0.1961, 0.9276, 0.2169, 0.3547]], dtype=torch.float64)


In [6]:
# Tensor Manipulation - Numpy

# Tensor to Numpy
tensor = torch.rand(3,4)
np_data = tensor.numpy()

print(f"Tensor Data:\n{tensor}\n")
print(f"NumPy Data:\n{np_data}")

Tensor Data:
tensor([[0.2406, 0.4645, 0.0242, 0.5214],
        [0.1784, 0.9541, 0.5958, 0.8028],
        [0.1910, 0.5012, 0.3807, 0.5303]])

NumPy Data:
[[0.24055028 0.4644645  0.02418399 0.52137375]
 [0.17838156 0.95411336 0.5958127  0.8028435 ]
 [0.19095814 0.5011712  0.3806517  0.5303484 ]]


In [7]:
# Numpy to Tensor
np_data = np.random.rand(3,4)
tensor = torch.tensor(np_data)

print(f"NumPy Data:\n{np_data}\n")
print(f"Tensor Data:\n{tensor}")

NumPy Data:
[[0.50861989 0.68808336 0.89901478 0.25372789]
 [0.41099555 0.35407704 0.59739032 0.09282974]
 [0.38882186 0.74619994 0.34778961 0.3354173 ]]

Tensor Data:
tensor([[0.5086, 0.6881, 0.8990, 0.2537],
        [0.4110, 0.3541, 0.5974, 0.0928],
        [0.3888, 0.7462, 0.3478, 0.3354]], dtype=torch.float64)


#### TENSOR ARITHMATICS

In [8]:
# Addition

tensor = torch.tensor([2,5,3])
tensor+100

tensor([102, 105, 103])

In [9]:
# Multiplication

tensor = tensor * 5
tensor

tensor([10, 25, 15])

In [10]:
# Subtraction

tensor = tensor - 50
tensor

tensor([-40, -25, -35])

In [11]:
# Division

tensor = tensor / 20
tensor

tensor([-2.0000, -1.2500, -1.7500])

In [12]:
# PyTorch In-build

tensor = torch.tensor([2,5,3])

tensor = torch.mul(tensor, 15)
print(f"In-build Multiplication:\n{tensor}")
tensor = torch.add(tensor, 100)
print(f"\nIn-build Addition:\n{tensor}")
tensor = torch.sub(tensor, 50)
print(f"\nIn-build Subtraction:\n{tensor}")
tensor = torch.div(tensor, 20)
print(f"\nIn-build Division:\n{tensor}")

In-build Multiplication:
tensor([30, 75, 45])

In-build Addition:
tensor([130, 175, 145])

In-build Subtraction:
tensor([ 80, 125,  95])

In-build Division:
tensor([4.0000, 6.2500, 4.7500])
