## Matrix Multiplication
1. Element-wise Multiplication (a.k.a Hadamard Product)
2. Matrix Multiplication

In [2]:
import torch
import numpy as np
import pandas as pd

#### Simple element-wise multiplication or, Hadamard product

<img src="../resources/Hadamard_Product.jpg" width=70%></img>

In [3]:
a = torch.tensor([2,4,6])
b = torch.tensor([1,3,5])

print(a,"*", b)
print(f"Equals:\t{a*b}")

tensor([2, 4, 6]) * tensor([1, 3, 5])
Equals:	tensor([ 2, 12, 30])


In [4]:
list_a = [2,4,6],[1,3,5],[7,8,9]
list_b = [1,3,5],[6,7,8],[2,4,9]

a = torch.tensor(list_a)
b = torch.tensor(list_b)

print(f"Matrix A * Matrix B =\n{a}\n{b}")
print(f"Equals =\n{a*b}")

Matrix A * Matrix B =
tensor([[2, 4, 6],
        [1, 3, 5],
        [7, 8, 9]])
tensor([[1, 3, 5],
        [6, 7, 8],
        [2, 4, 9]])
Equals =
tensor([[ 2, 12, 30],
        [ 6, 21, 40],
        [14, 32, 81]])


### Matrix Multiplication

<img src="../resources/Matrix_Multiplication.gif" width=40%></img>

In [21]:
mat_a = [1,2,3],[4,5,6]
mat_b = [7,8],[9,10],[11,12]

a = torch.tensor(mat_a)
b = torch.tensor(mat_b)

print(f"Matrix A ⠐ Matrix B =\n{a}\n{b}")
print(f"Equals =\n{torch.matmul(a,b)}")

Matrix A ⠐ Matrix B =
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
Equals =
tensor([[ 58,  64],
        [139, 154]])


<b>Matrix multiplication can be done with loops. But the torch version of matrix multiplication is more time, complexity and space efficient. <br/> Let's have a look on how it works...</b>

In [22]:
# Matrix calculation by hand

c00 = a[0,0]*b[0,0] + a[0,1]*b[1,0] + a[0,2]*b[2,0]
c01 = a[0,0]*b[0,1] + a[0,1]*b[1,1] + a[0,2]*b[2,1]
c10 = a[1,0]*b[0,0] + a[1,1]*b[1,0] + a[1,2]*b[2,0]
c11 = a[1,0]*b[0,1] + a[1,1]*b[1,1] + a[1,2]*b[2,1]

print(f"Equals =\n[ [ {c00},  {c01}]\n  [{c10}, {c11}] ]\n\n")

Equals =
[ [ 58,  64]
  [139, 154] ]




In [23]:
%%time
# Initialize result matrix with zeros
result = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]

# Perform matrix multiplication
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            result[i][j] += a[i][k] * b[k][j]
print("===== Matrix Multiplication with `for` loops =====\n")
print(f"Matrix A ⠐ Matrix B =\n{a}⠐\n{b}")
print(f"Equals:\n{result[0]},\n{result[1]}\n\n")

===== Matrix Multiplication with `for` loops =====

Matrix A ⠐ Matrix B =
tensor([[1, 2, 3],
        [4, 5, 6]])⠐
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
Equals:
[tensor(58), tensor(64)],
[tensor(139), tensor(154)]


CPU times: total: 0 ns
Wall time: 2 ms


In [24]:
%%time
print("===== Matrix Multiplication with torch =====\n")
print(f"Matrix A ⠐ Matrix B =\n{a}⠐\n{b}")
print(f"Equals:\n{torch.matmul(a,b)}\n\n")

===== Matrix Multiplication with torch =====

Matrix A ⠐ Matrix B =
tensor([[1, 2, 3],
        [4, 5, 6]])⠐
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
Equals:
tensor([[ 58,  64],
        [139, 154]])


CPU times: total: 0 ns
Wall time: 1 ms


<b>
As we can see, the wall time of Matrix multiplication with for loops is greater than the wall time of Matrix multiplication with torch function `matmul`.<br/>
</b>

```
2 ms > 998 µs
```