## Matrix Multiplication
1. Element-wise Multiplication (a.k.a Hadamard Product)
2. Matrix Multiplication

In [10]:
import torch
import numpy as np
import pandas as pd

#### Simple element-wise multiplication or, Hadamard product

<img src="../resources/Hadamard_Product.jpg" width=70%></img>

In [11]:
a = torch.tensor([2,4,6])
b = torch.tensor([1,3,5])

print(a,"*", b)
print(f"Equals:\t{a*b}")

tensor([2, 4, 6]) * tensor([1, 3, 5])
Equals:	tensor([ 2, 12, 30])


In [12]:
list_a = [2,4,6],[1,3,5],[7,8,9]
list_b = [1,3,5],[6,7,8],[2,4,9]

a = torch.tensor(list_a)
b = torch.tensor(list_b)

print(f"Matrix A * Matrix B =\n{a}\n{b}")
print(f"Equals =\n{a*b}")

Matrix A * Matrix B =
tensor([[2, 4, 6],
        [1, 3, 5],
        [7, 8, 9]])
tensor([[1, 3, 5],
        [6, 7, 8],
        [2, 4, 9]])
Equals =
tensor([[ 2, 12, 30],
        [ 6, 21, 40],
        [14, 32, 81]])


### Matrix Multiplication

<img src="../resources/Matrix_Multiplication.gif" width=40%></img>

In [13]:
mat_a = [1,2,3],[4,5,6]
mat_b = [7,8],[9,10],[11,12]

a = torch.tensor(mat_a)
b = torch.tensor(mat_b)

print(f"Matrix A ⠐ Matrix B =\n{a}\n{b}")
print(f"Equals =\n{torch.matmul(a,b)}")

Matrix A ⠐ Matrix B =
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
Equals =
tensor([[ 58,  64],
        [139, 154]])


<b>Matrix multiplication can be done with loops. But the torch version of matrix multiplication is more time, complexity and space efficient. <br/> Let's have a look on how it works...</b>

In [14]:
# Matrix calculation by hand

c00 = a[0,0]*b[0,0] + a[0,1]*b[1,0] + a[0,2]*b[2,0]
c01 = a[0,0]*b[0,1] + a[0,1]*b[1,1] + a[0,2]*b[2,1]
c10 = a[1,0]*b[0,0] + a[1,1]*b[1,0] + a[1,2]*b[2,0]
c11 = a[1,0]*b[0,1] + a[1,1]*b[1,1] + a[1,2]*b[2,1]

print(f"Equals =\n[ [ {c00},  {c01}]\n  [{c10}, {c11}] ]\n\n")

Equals =
[ [ 58,  64]
  [139, 154] ]




In [15]:
%%time
# Initialize result matrix with zeros
result = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]

# Perform matrix multiplication
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            result[i][j] += a[i][k] * b[k][j]
print("===== Matrix Multiplication with `for` loops =====\n")
print(f"Matrix A ⠐ Matrix B =\n{a}⠐\n{b}")
print(f"Equals:\n{result[0]},\n{result[1]}\n\n")

===== Matrix Multiplication with `for` loops =====

Matrix A ⠐ Matrix B =
tensor([[1, 2, 3],
        [4, 5, 6]])⠐
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
Equals:
[tensor(58), tensor(64)],
[tensor(139), tensor(154)]


CPU times: total: 0 ns
Wall time: 3 ms


In [16]:
%%time
print("===== Matrix Multiplication with torch =====\n")
print(f"Matrix A ⠐ Matrix B =\n{a}⠐\n{b}")
print(f"Equals:\n{torch.matmul(a,b)}\n\n")

===== Matrix Multiplication with torch =====

Matrix A ⠐ Matrix B =
tensor([[1, 2, 3],
        [4, 5, 6]])⠐
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
Equals:
tensor([[ 58,  64],
        [139, 154]])


CPU times: total: 0 ns
Wall time: 996 µs


<b>
As we can see, the wall time of Matrix multiplication with for loops is greater than the wall time of Matrix multiplication with torch function `matmul`.<br/>
</b>

```
3 ms > 996 µs
```

#### ! IMPORTANT: RULES OF PERFORMING MATRIX MULTIPLICATION
There are 2 main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
    * `(3, 2) @ (3, 2)` won't work
    * `(3, 3) @ (3, 1)` will work
    * `(2, 3) @ (3, 3)` will work
    * `(2, 2) @ (3, 3)` won't work

2. The resulting matrix has the shape of the **outer dimensions**:
    * `(3, 3) @ (3, 1)` resulting shape --> (3, 1)
    * `(2, 3) @ (3, 3)` resulting shape --> (2, 3)
    * `(1, 3) @ (3, 2)` resulting shape --> (1, 2)

### Common Errors in Deep Learning
* Shape Error/ Shape Mismatch

In [17]:
 # Shapes for Matrix Multiplication

tensor_A = torch.tensor([[2, 4],
                         [6, 1],
                         [3, 9]])  # 3x2 matrix

tensor_B = torch.tensor([[-1, 8],
                         [4, 0],
                         [3, -5]]) # 3x2 matrix

In [18]:
# torch.mm() is an alias of torch.matmul()
matmul = torch.mm(tensor_A, tensor_B) # There will be shape error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [24]:
# Let's see the reason behind the error
print(f"(Tensor_A Shape, Tensor_B Shape) = {tensor_A.shape, tensor_B.shape}")

(Tensor_A Shape, Tensor_B Shape) = (torch.Size([3, 2]), torch.Size([3, 2]))


In [25]:
# Let's do transpose of Tensor_B to match inner dimension

tensor_Bt = tensor_B.T
print(f"tensor_B Transpose:\n{tensor_Bt}\n")
print(f"Shape: {tensor_Bt.shape[0],tensor_Bt.shape[1]}")

tensor_B Transpose:
tensor([[-1,  4,  3],
        [ 8,  0, -5]])

Shape: (2, 3)


In [28]:
# Let's see the new shapes
print(f"(Tensor_A Shape, Tensor_B Transposed Shape) = \n{tensor_A.shape, tensor_Bt.shape}")

(Tensor_A Shape, Tensor_B Transposed Shape) = 
(torch.Size([3, 2]), torch.Size([2, 3]))


In [31]:
# Now let's try the matrix multiplication again
matmul = torch.mm(tensor_A, tensor_Bt) # inner dimension matched

print(f"Matrix Multiplication Output:\n {matmul}")
print(f"\nNew Shape of the Output Matrix: {matmul.shape[0],matmul.shape[1]}")

Matrix Multiplication Output:
 tensor([[ 30,   8, -14],
        [  2,  24,  13],
        [ 69,  12, -36]])

New Shape of the Output Matrix: (3, 3)


##### More Example

In [41]:
matA = torch.tensor([[0, 0, 1],
                    [1, 1, 0]])

matB = torch.tensor([[1, 0],
                    [1, 1],
                    [0, 1],
                    [0, 0]])

matC = torch.tensor([[1],
                    [0],
                    [1],
                    [0]])

matD = torch.tensor([[0, 0, 0, 1],
                    [0, 0, 1, 1],
                    [0, 1, 0, 0],
                    [1, 1, 0, 0]])

In [42]:
print(matA, matA.shape,"\n")
print(matB, matB.shape,"\n")
print(matC, matC.shape,"\n")
print(matD, matD.shape,"\n")

tensor([[0, 0, 1],
        [1, 1, 0]]) torch.Size([2, 3]) 

tensor([[1, 0],
        [1, 1],
        [0, 1],
        [0, 0]]) torch.Size([4, 2]) 

tensor([[1],
        [0],
        [1],
        [0]]) torch.Size([4, 1]) 

tensor([[0, 0, 0, 1],
        [0, 0, 1, 1],
        [0, 1, 0, 0],
        [1, 1, 0, 0]]) torch.Size([4, 4]) 



In [43]:
print("MatA & MatB Transposed Shape:",matA.T.shape, matB.T.shape)
matAt_Bt = torch.mm(matA.T, matB.T)
print("\n",matAt_Bt,matAt_Bt.shape)

MatA & MatB Transposed Shape: torch.Size([3, 2]) torch.Size([2, 4])

 tensor([[0, 1, 1, 0],
        [0, 1, 1, 0],
        [1, 1, 0, 0]]) torch.Size([3, 4])


In [44]:
print("MatC Transposed & MatD Shape:",matC.T.shape, matD.shape)
matCt_D = torch.mm(matC.T, matD)
print("\n",matCt_D,matCt_D.shape)

MatC Transposed & MatD Shape: torch.Size([1, 4]) torch.Size([4, 4])

 tensor([[0, 1, 0, 1]]) torch.Size([1, 4])


In [45]:
print("MatAt & MatCt Transposed Shape:",matAt_Bt.shape, matCt_D.T.shape)
matE = torch.mm(matAt_Bt, matCt_D.T)
print("\n",matE,matE.shape)

MatAt & MatCt Transposed Shape: torch.Size([3, 4]) torch.Size([4, 1])

 tensor([[1],
        [1],
        [1]]) torch.Size([3, 1])


In [54]:
# Transpose of MatE
print(f"Transposed Mat_E \t= {matE.T}")
print(f"Transposed Mat_E Shape \t= {matE.T.shape[0],matE.T.shape[1]}")

Transposed Mat_E 	= tensor([[1, 1, 1]])
Transposed Mat_E Shape 	= (1, 3)


### <------------------ END OF NOTEBOOK ------------------>
#### ==================================== ~`MUBA`~ ==