## Tesnor Aggregations
* Minimum (min)
* Maximum (max)
* Mean/Average (mean)
* Summation (sum)
* Positional Minima (argmin)
* Positional Maxima (argmax)

In [2]:
import torch
import numpy as np
import pandas as pd

In [3]:
# Create a tensor
x = torch.arange(0, 500, 5)
print(f"Tensor X = \n{x}\nTensor X Shape = {x.shape}")


Tensor X = 
tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
        140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205,
        210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275,
        280, 285, 290, 295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345,
        350, 355, 360, 365, 370, 375, 380, 385, 390, 395, 400, 405, 410, 415,
        420, 425, 430, 435, 440, 445, 450, 455, 460, 465, 470, 475, 480, 485,
        490, 495])
Tensor X Shape = torch.Size([100])


#### Minimum (min)

In [4]:
# Find the minimum (min)
min = x.min()
print(f'Minimum by x.min()\t: {min}')
min = torch.min(x)
print(f'Minimum by torch.min(x)\t: {min}')

Minimum by x.min()	: 0
Minimum by torch.min(x)	: 0


#### Maximum (max)

In [5]:
# Find the maximum (max)
max = x.max()
print(f'Maximum by x.max()\t: {max}')
max = torch.max(x)
print(f'Maximum by torch.max(x)\t: {max}')

Maximum by x.max()	: 495
Maximum by torch.max(x)	: 495


#### Mean/Average (mean)

In [6]:
## Here we might see a dtype error for the first time. As mean() function 
## cannot work on long dtype, which is int64.

mean = torch.mean(x)
print(f"Mean of Tensor X\t: {mean}")

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

The `torch.mean()` function requires a tensor of float32 dtype to work

In [7]:
# To solve this error, we can trigger the optional dtype parameter of mean()

mean = torch.mean(x, dtype=float)
print(f"Mean of Tensor X by torch.mean(dtype) :\t{mean}")
mean = x.mean(dtype=float)
print(f"Mean of Tensor X by x.mean(dtype) :\t{mean}\n")

# OR

mean = torch.mean(x.type(torch.float32))
print(f"Mean of Tensor X by torch.mean(type) :\t{mean}")
mean = x.type(torch.float32).mean()
print(f"Mean of Tensor X by x.mean(type) : \t{mean}")

Mean of Tensor X by torch.mean(dtype) :	247.5
Mean of Tensor X by x.mean(dtype) :	247.5

Mean of Tensor X by torch.mean(type) :	247.5
Mean of Tensor X by x.mean(type) : 	247.5


#### Summation (sum)

In [8]:
# Find the summation (sum)
sum = x.sum()
print(f'Summation by x.sum()\t\t: {sum}')
sum = torch.sum(x)
print(f'Summation by torch.sum(x)\t: {sum}')

Summation by x.sum()		: 24750
Summation by torch.sum(x)	: 24750


#### Positional Minima (argmin) & Positional Maxima (argmax)

In [9]:
# Find the index of the tensor with minimum and maximum value
argmin = x.argmin()
print(f"The Minimum Value is `{x.min()}` and the index is `{argmin}`")

argmax = x.argmax()
print(f"The Maximum Value is `{x.max()}` and the index is `{argmax}`")

The Minimum Value is `0` and the index is `0`
The Maximum Value is `495` and the index is `99`


## Tensor Modifications
* **Reshaping** - Reshapes an input tensor to a defined shape
* **View** - Return a view of an input tensor of certain shape, but keep the original one
* **Stacking** - Combine multiple tensors on top of each other
    * Veertical Stack
    * Horizontal Stack
* **Squeezing** - Removes all in `1` dimension from a tensor 
* **Unsqueezing** - Add a `1` dimension to a target tensor
* **Permute** - Return a view of the input with dimensions permuted (swapped) in a certain way

In [19]:
# Let's create a tensor
a = torch.arange(1., 10.)
a, a.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

#### Reshaping
To reshape any tensor, we have to abide by two rules:
* The multiplication of new shapes should be same as the original shape
* The new shape should be a Multiplier of the original shape

In [20]:
print(f"Original :\n {a}\nShape :\t{a.shape}\n")

a_reshaped1 = a.reshape(1, 9)
print(f"Reshaped ({a_reshaped1.shape[0]} x {a_reshaped1.shape[1]}):\n {a_reshaped1}\nShape :\t{a_reshaped1.shape}\n")

a_reshaped2 = a.reshape(3, 3)
print(f"Reshaped ({a_reshaped2.shape[0]} x {a_reshaped2.shape[1]}):\n {a_reshaped2}\nShape :\t{a_reshaped2.shape}\n")

a_reshaped3 = a.reshape(9, 1)
print(f"Reshaped ({a_reshaped3.shape[0]} x {a_reshaped3.shape[1]}):\n {a_reshaped3}\nShape :\t{a_reshaped3.shape}\n")


Original :
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Shape :	torch.Size([9])

Reshaped (1 x 9):
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Shape :	torch.Size([1, 9])

Reshaped (3 x 3):
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Shape :	torch.Size([3, 3])

Reshaped (9 x 1):
 tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Shape :	torch.Size([9, 1])



#### View
View is almost similar to Reshape. The difference is **Reshaping a tensor variable allots another new tensor in the memory, while Viewing a tensor variable shares the same original tensor in the memory**. This means, changing the View variable will ultimately change the original tensor.

In [21]:
# Let's change the view
b = a.view(3,3)
b, b.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [22]:
# Let's change the tensor variable `b` to see any change in variable `a`

b[:, 0] = 10
b, a

(tensor([[10.,  2.,  3.],
         [10.,  5.,  6.],
         [10.,  8.,  9.]]),
 tensor([10.,  2.,  3., 10.,  5.,  6., 10.,  8.,  9.]))

Here, the tensor variable `b`'s first index value was changed to `10` and we can see the original tensor variable `a`'s first index was also changed.<br>
But notice how the shape and every positional index of tensor `b` has changed the original variable `a`.

#### Stacking
* **Vertical Stack (vstack) alias `row_stack`** - stacks each tensors vertically (row-wise)
* **Horizontal Stack (hstack) alias `column_stack`** - stacks each tensors horizontally (column-wise)


In [23]:
# Stack tensors on top of each other
x = torch.arange(1,100,10)
print(f"Original Tensor:\t{x}\nOriginal Tensor Shape:\t{x.ndim, x.shape[0]}\n")

Original Tensor:	tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
Original Tensor Shape:	(1, 10)



In [24]:
x_stacked = torch.vstack([x,x,x]) # torch.row_stack([x,x,x])
print(f"V-Stacked Tensor:\n{x_stacked}\nTensor Shape:\t{x_stacked.shape}\n")

x_stacked = torch.hstack([x,x,x]) # torch.column_stack([x,x,x])
print(f"H-Stacked Tensor:\n{x_stacked}\nTensor Shape:\t{x_stacked.shape}\n")

V-Stacked Tensor:
tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])
Tensor Shape:	torch.Size([3, 10])

H-Stacked Tensor:
tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91,  1, 11, 21, 31, 41, 51, 61, 71,
        81, 91,  1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
Tensor Shape:	torch.Size([30])



In [25]:
x_stacked = torch.stack([x, x, x], dim=0)
print(f"Stacked dim=0 Tensor:\n{x_stacked}\nTensor Shape:\t{x_stacked.shape}\n")

x_stacked = torch.stack([x, x, x], dim=1)
print(f"Stacked dim=1 Tensor:\n{x_stacked}\nTensor Shape:\t{x_stacked.shape}\n")

Stacked dim=0 Tensor:
tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
        [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])
Tensor Shape:	torch.Size([3, 10])

Stacked dim=1 Tensor:
tensor([[ 1,  1,  1],
        [11, 11, 11],
        [21, 21, 21],
        [31, 31, 31],
        [41, 41, 41],
        [51, 51, 51],
        [61, 61, 61],
        [71, 71, 71],
        [81, 81, 81],
        [91, 91, 91]])
Tensor Shape:	torch.Size([10, 3])



#### Squeeze and Unsqueeze
`torch.squeeze` removes all 1 dimension from a tensor<br>
`torch.unsqueeze` adds a single dimension to a tensor

In [26]:
print(f"Original Tensor : \n{x}\nShape : {x.shape}\n")
x_reshaped = x.reshape(1,10)
print(f"\nReshaped Tensor : \n{x_reshaped}\nShape : {x_reshaped.shape}\n")

x_squeezed = x_reshaped.squeeze()
print(f"\nSqueezed Tensor : \n{x_squeezed}\nShape : {x_squeezed.shape}\n")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nUnsqueezed Tensor dim=0 : \n{x_unsqueezed}\nShape : {x_unsqueezed.shape}\n")

x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nUnsqueezed Tensor dim=1 : \n{x_unsqueezed}\nShape : {x_unsqueezed.shape}\n")

Original Tensor : 
tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
Shape : torch.Size([10])


Reshaped Tensor : 
tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])
Shape : torch.Size([1, 10])


Squeezed Tensor : 
tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
Shape : torch.Size([10])


Unsqueezed Tensor dim=0 : 
tensor([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])
Shape : torch.Size([1, 10])


Unsqueezed Tensor dim=1 : 
tensor([[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]])
Shape : torch.Size([10, 1])



#### Permute
`torch.permute()` returns a view of the original tensor `input` with its dimension permuted (swapped).

In [27]:
# A image tensor with [(height, width, channel)]
img = torch.rand(size=(224,224,3)) # Tensor index = (0, 1, 2)

# Permute the original image tensor to rearrange the axis (or dim) order
img_permuted = img.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous Image Shape : {img.shape}")
print(f"Permuted Image Tensor :\n {img_permuted}\n")
print(f"Permuted Image Shape : {img_permuted.shape}")

Previous Image Shape : torch.Size([224, 224, 3])
Permuted Image Tensor :
 tensor([[[0.2767, 0.8531, 0.9216,  ..., 0.2231, 0.8482, 0.0695],
         [0.5313, 0.5851, 0.9939,  ..., 0.9300, 0.0031, 0.0762],
         [0.1663, 0.5802, 0.4238,  ..., 0.8256, 0.2081, 0.2557],
         ...,
         [0.6558, 0.1014, 0.3109,  ..., 0.6864, 0.4144, 0.8503],
         [0.6778, 0.3108, 0.2122,  ..., 0.4678, 0.7675, 0.3764],
         [0.4796, 0.7514, 0.1595,  ..., 0.7988, 0.2960, 0.1693]],

        [[0.8730, 0.4989, 0.1346,  ..., 0.5951, 0.1721, 0.7872],
         [0.5796, 0.6862, 0.8995,  ..., 0.8133, 0.2002, 0.7135],
         [0.5267, 0.9734, 0.3419,  ..., 0.1677, 0.8896, 0.1285],
         ...,
         [0.0052, 0.0590, 0.6771,  ..., 0.9455, 0.1797, 0.8420],
         [0.6533, 0.9132, 0.8192,  ..., 0.0965, 0.5183, 0.2370],
         [0.0708, 0.1032, 0.3494,  ..., 0.2658, 0.6531, 0.6453]],

        [[0.3161, 0.1232, 0.1203,  ..., 0.9517, 0.4038, 0.1736],
         [0.1839, 0.2240, 0.2866,  ..., 0.0039, 0

In [28]:
# Extras
print(f"Previous Original Tensor[0,0,0] Value :\t{img[0,0,0]}")
print(f"Previous Permuted Tensor[0,0,0] Value :\t{img_permuted[0,0,0]}")

img[0,0,0] = 123456.
img_permuted = img.permute(2, 0, 1)

print(f"Updated Original Tensor[0,0,0] Value :\t{img[0,0,0]}")
print(f"Updated Permuted Tensor[0,0,0] Value :\t{img_permuted[0,0,0]}")


Previous Original Tensor[0,0,0] Value :	0.276655375957489
Previous Permuted Tensor[0,0,0] Value :	0.276655375957489
Updated Original Tensor[0,0,0] Value :	123456.0
Updated Permuted Tensor[0,0,0] Value :	123456.0


### Tensor Indexing : Selecting Data From Tensors

The tensor shape belongs to three properties:
- Element: The element in each index of the tensor
- Index: The index of tensor in a dimension
- Tensor: The tensor itself
</br></br>
*Tensor Shape([Number of Tensors, Number of Indices, Number of Elements])*
</br>
As per the shape of tensor: <br>`tensor.shape([1,3,3]) = tensor.shape([1 Tensor, 3 Index, 3 Elements])`

<img src="../resources/Tensor_Indexing.jpg" width=85%></img>

In [16]:
# Create a Tensor
import torch

x = torch.arange(1, 10).reshape(1,3,3)
print(f"Original Tensor:\n {x}\nShape:\t{x.shape}\n")

Original Tensor:
 tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape:	torch.Size([1, 3, 3])



In [17]:
# Index the tensor in 0-th dimension (dim=0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

It gives the zeroth tensor at the zeroth dimension of the whole tensor

In [18]:
# Index the tensor in 1st dimension (dim=1)
x[0][0]

tensor([1, 2, 3])

It gives the zeroth index of the zeroth tensor at the zeroth dimension of the whole tensor

In [19]:
# Index the tensor in 2nd dimension (dim=2) [last dimension]
x[0][0][0]

tensor(1)

In [26]:
# Let's index some more tensor

print(f"2nd Index of the Zeroth Tensor: {x[0][1]}\n")
print(f"3rd Element of the 1st Index of the Zeroth Tensor: {x[0][0][2]}\n")
print(f"Last Element of the last Index of the Zeroth Tensor: {x[0][2][2]}\n")
print(f"3rd Index of the Zeroth Tensor: {x[0][2]}\n")

2nd Index of the Zeroth Tensor: tensor([4, 5, 6])

3rd Element of the 1st Index of the Zeroth Tensor: 3

Last Element of the last Index of the Zeroth Tensor: 9

3rd Index of the Zeroth Tensor: tensor([7, 8, 9])



In [45]:
# You can also use ":" to select "all" of the targeted dimension
x = torch.arange(1, 19).reshape(2,3,3)

print(x, "\n", x.shape)
print(f"\n\nSelect all the tensor's zeroth indices = x[:, 0]\n{x[:, 0]}\n")
print(f"Select all the tensor's 2nd index's 2nd elements = x[:,1,2]\n{x[:,1,2]}\n")
print(f"Select 2nd tensor's 1st index's al elements = x[1,0,:]\n{x[1,0,:]}\n")
print(f"Select all tensor's all indices last element = x[:, :,-1]\n{x[:, :,-1]}\n")
print(f"Select last tensor's last index's last element = x[-1,-1,-1]\n{x[-1,-1,-1]}\n")
print(f"Select 1st tensor's all indices last elements = x[0,:,-1]\n{x[0,:,-1]}\n")

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]) 
 torch.Size([2, 3, 3])


Select all the tensor's zeroth indices = x[:, 0]
tensor([[ 1,  2,  3],
        [10, 11, 12]])

Select all the tensor's 2nd index's 2nd elements = x[:,1,2]
tensor([ 6, 15])

Select 2nd tensor's 1st index's al elements = x[1,0,:]
tensor([10, 11, 12])

Select all tensor's all indices last element = x[:, :,-1]
tensor([[ 3,  6,  9],
        [12, 15, 18]])

Select last tensor's last index's last element = x[-1,-1,-1]
18

Select 1st tensor's all indices last elements = x[0,:,-1]
tensor([3, 6, 9])



It  gives the zeroth element of the zeroth index's zeroth tensor at the zeroth dimension of the whole tensor

<h1 align="center">--< THE END >--</h1> 
@MUBA