## Tensors & Numpy

NumPy is generally used to express data in scientific computation and PyTorch has its own functionality to interact with NumPy.
* Data in NumPy, want to convert into PyTorch Tensor --> `torch.from_numpy(ndarray)`
* Data in Tensor, want to convert into Numpy Array --> `torch.Tensor.numpy()`

#### Tensor --> Numpy

In [1]:
import torch
import numpy as np 

# Create an array in Numpy
array = np.arange(1.,8.)
tensor = torch.from_numpy(array)

print(f"Numpy Array:\t{array}\nTorch Tensor:\t{tensor}")

Numpy Array:	[1. 2. 3. 4. 5. 6. 7.]
Torch Tensor:	tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


#### Numpy --> Tensor

In [2]:
tensor = torch.ones(5)
array = tensor.numpy()

print(f"Torch Tensor:\t{tensor}\nNumpy Array:\t{array}\n")

Torch Tensor:	tensor([1., 1., 1., 1., 1.])
Numpy Array:	[1. 1. 1. 1. 1.]



** **Note For Use** **<br>
The default dtype of tensor is `float64` and the default dtype of numpy is `float32`. So, while converting them, please make sure which dtype are you going to use.

In [3]:
# Let's reconvert the numpy array to a tensor
tensor = torch.from_numpy(array)
array = tensor.numpy()

print(f"Numpy Array:\t{array, array.dtype}\nTorch Tensor:\t{tensor, tensor.dtype}")

Numpy Array:	(array([1., 1., 1., 1., 1.], dtype=float32), dtype('float32'))
Torch Tensor:	(tensor([1., 1., 1., 1., 1.]), torch.float32)


### PyTorch Reproducibility
To reuce the randomness of random tensors using `RANDOM_SEED`.

In [4]:
tensorA = torch.rand(4,4)
tensorB = torch.rand(4,4)

print(f"Tensor A:\n{tensorA}\nTensor B:\n{tensorB}\nCheck Equality:")
print(tensorA == tensorB)

Tensor A:
tensor([[0.8548, 0.0240, 0.4702, 0.1620],
        [0.5360, 0.4982, 0.6276, 0.0910],
        [0.2159, 0.0260, 0.9612, 0.7533],
        [0.7190, 0.4091, 0.2797, 0.6428]])
Tensor B:
tensor([[0.3312, 0.5153, 0.2986, 0.8596],
        [0.8950, 0.9578, 0.7068, 0.4536],
        [0.2630, 0.9686, 0.8441, 0.0318],
        [0.3516, 0.6056, 0.8034, 0.7945]])
Check Equality:
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


With normal tensors without `random seed` it shows complete randomness while producing random tensors.

In [5]:
# Set the random seed
RANDOM_SEED = 123
torch.manual_seed(RANDOM_SEED)
tensorC = torch.rand(4,4)
torch.manual_seed(RANDOM_SEED)
tensorD = torch.rand(4,4)

print(f"Tensor C:\n{tensorC}\nTensor D:\n{tensorD}\nCheck Equality:")
print(tensorC == tensorD)

Tensor C:
tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871],
        [0.0756, 0.1966, 0.3164, 0.4017]])
Tensor D:
tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871],
        [0.0756, 0.1966, 0.3164, 0.4017]])
Check Equality:
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running Tensors on GPUs

GPUs make faster and lighter computations on numbers by using `CUDA` with `NVIDIA` hardware.

In [6]:
# GPU Access check
import torch
torch.cuda.is_available()

True

In [7]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device:\t{device}")

Device:	cuda


In [8]:
# Count the number of active GPUs
torch.cuda.device_count()

1

In [9]:
# Putting tensors (and models) on the GPU
import torch
tensor = torch.tensor([1,2,3]) # By default device is on CPU
print(f"Tensor:\t{tensor}\nDevice:\t{tensor.device}")

Tensor:	tensor([1, 2, 3])
Device:	cpu


In [10]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
print(f"Tensor:\t{tensor_on_gpu}")

Tensor:	tensor([1, 2, 3], device='cuda:0')


#### Moving tensors back to CPU

In [11]:
# Tensors cannot transform tensors on GPUs, therefore error will occur
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [16]:
# To fix the GPU tensor with NumPy issue, we can set it to the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(f"Tensor on CPU in Numpy: \t{tensor_back_on_cpu}")
print(f"Tensor on GPU in PyTorch:\t{tensor_on_gpu}")

Tensor on CPU in Numpy: 	[1 2 3]
Tensor on GPU in PyTorch:	tensor([1, 2, 3], device='cuda:0')


<h1 align="center">--< THE END >--</h1> 
@MUBA